### ISSUE TITLE
canner dose not run in Docker

### ISSUE THREAD

**Issue by charlitoro** [Canner/canner-quick-start#1]
I want to create a docker container with this base project, but this container not export the port.
The **docker-compose.yml**:
```
version: '3.3'
services:
    cms-node:
        build: .
        container_name: cms-node 
        volumes:
            - ./:/usr/app/
            - /usr/app/node_modules
        command: bash -c "yarn install && yarn start"
        ports:
            - 3000:8080
    
```
I think that this problem is about webpack...
